# Generated by Django 3.1.2 on 2020-10-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='data_criancao',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='contato',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
