# Generated by Django 3.1.2 on 2020-10-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_auto_20201003_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='data_criacao',
            new_name='data_criação',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='descricao',
            new_name='descrição',
        ),
    ]
