# Generated by Django 3.1.2 on 2020-10-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_contato_mostra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='mostra',
            new_name='mostrar',
        ),
    ]
